#!/bin/bash
#
# Script Name:  remove
# Description: 	Safely move file to $HOME/deleted 
# Author:  Yangyang Ma
# History: 2019-Sep-25 Initial
#	   2019-Sep-27 v4    
#
# Example: bash remove filename or ./remove filename
#

#====================================
#
# Global Variables
#====================================
INPUT_FILE=$1
RECYLE_DIR="$HOME/deleted"
RESTORE_INFO="$HOME/.restore.info"

#=====================================
# Check Arguments
# -- Only 1 argument allowed
# -- Only filename allowed
# -- Directory is NOT allowed
#=====================================

if [ $# -eq 0 ]
then
	echo -e "\nFile name not found!\n"
	echo -e "\tExample: bash `basename $0` filename\n"
	exit 1
elif [ $# -gt 1 ]
then
	echo -e "\nOnly one file name allowed\n"
	echo -e "\tExample: bash `basename $0` filename\n"
	exit 1
fi


if [ -d $INPUT_FILE ]
then
	echo -e "\nRemove directory is not allowed!\n"
	exit 1
fi


if [ ! -f $INPUT_FILE ]
then
	echo -e "\n$INPUT_FILE not found!\n"
	exit 1
fi

# Self remove is not allowed
if [ `basename $INPUT_FILE` == `basename $0` ]
then
	echo -e "\nSelf-remove \"`basename $0`\" is not allowed!\n"
	exit 1

fi 

#=========================================
# Create $HOME/deleted if it doesn't exist
#=========================================
if [ ! -d $RECYLE_DIR ]
then
	mkdir $RECYLE_DIR
fi


#===============================================
# Create $HOME/.restore.info if it doesn't exist
#===============================================
if [ ! -f $RESTORE_INFO ]
then
	touch $RESTORE_INFO
fi	


#====================================================
# Move $INPUT_FILE to $HOME/deleted/$INPUT_FILE_inode
# Log to $HOME/.restore.info
#====================================================

## Involve realpath to get absolute path of the file
## realpath ../../tmp/testfile -> /tmp/testfile
REAL_PATH=`realpath $INPUT_FILE`
FILE_INODE=`ls -i $REAL_PATH|cut -d" " -f1`
NEW_FILENAME="`basename $REAL_PATH`"_"$FILE_INODE"
FILE_LOCATION=`dirname $REAL_PATH`

#move file to $HOME/deleted
mv -f $REAL_PATH $RECYLE_DIR/$NEW_FILENAME
if [ $? -eq 0 ]
then 
	echo -e "\nRemove $INPUT_FILE successfully!\n"
	echo "$NEW_FILENAME:$REAL_PATH" >>$RESTORE_INFO
	if [ $? -eq 0 ]
	then
		echo -e "Update $RESTORE_INFO successfully!\n"
	else 
		echo -e "Update $RESTORE_INFO failed!\n"
	fi
else
	echo  -e "\nRemove $INPUT_FILE failed!\n"
fi	
